kumuluzee:
  name: authentication-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/SharyCarDB
      connection-url: jdbc:postgresql://192.168.99.100:5432/postgres
      username: postgres
      password: postgres
      max-pool-size: 20